<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TalentFlow.Application\TalentFlow.Application.csproj" />
    <ProjectReference Include="..\TalentFlow.Domain\TalentFlow.Domain.csproj" />
  </ItemGroup>

</Project>
